name: C/C++ CI

on:
  push:
    branches: [ "feature/lc-data-entry" ]
  pull_request:
    branches: [ "feature/lc-data-entry" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure easy
      run: ./easy.sh
    - name: configure medium
      run: ./medium.sh
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
