name: C/C++ CI

on:
  push:
    branches: [ "feature/lc-data-entry" ]
  pull_request:
    branches: [ "feature/lc-data-entry" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Compile easy C++ files
      run: |
        if ls easy/*.cpp 1> /dev/null 2>&1; then
          for file in easy/*.cpp; do
            g++ -std=c++17 -Wall -Wno-sign-compare -Werror "$file" -o "${file%.cpp}.out"
          done
        else
          echo "No C++ files found in easy/"
        fi

    - name: Compile medium C++ files
      run: |
        if ls medium/*.cpp 1> /dev/null 2>&1; then
          for file in medium/*.cpp; do
            g++ -std=c++17 -Wall -Wno-sign-compare -Werror "$file" -o "${file%.cpp}.out"
          done
        else
          echo "No C++ files found in medium/"
        fi

    - name: make
      run: make

    - name: make check
      run: make check

    - name: make distcheck
      run: make distcheck
